### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0') in devContainersSpecCLI.js

### ISSUE THREAD

**Issue by 0xE1E10** [devcontainers-community/features-llvm#4]
https://github.com/devcontainers/cli/issues/699

Affects all tags latest, 3, 3.0, 3.0.0, empty. Cloning the repo locally solves the problem for some reasons.

**Comment by njelich** [comment]
Resolved in [v3.1.0](https://github.com/devcontainers-community/features-llvm/releases/tag/v3.1.0)
